---
title: "About me"
output: html_document
date: 2020-04-15
author: "Andrés Arau"
---


## Me

I am passionate about data visualization, interactive maps, and the use of data innovative approaches to facilate ongoing learning and adaptation of development programmes.

## I have lived in:

Mexico, Canada, Spain, US, Sweden, and UK.

## My professional experience expands over more than 26 projects across 21 countries worldwide:

Austria, Brazil, China, Colombia, Ecuador, Ghana, India, Kenya, Madagascar, Malawi, Mexico, Mozambique, Nigeria, Peru, Sierra Leone, South Africa, Uganda, United Kingdom, United States, Venezuela, and Vietnam.

## Have had the luck to work for these organizations in different projects:

* Ashoka
* Carlos Slim Foundation
* Department for Business, Energy and Industrial Strategy (UK)
* Department for International Development (UK)
* Development Research Group
* Fundacion IDEA /C230 Consultores
* Inter-American Development Bank
* International Atomic Energy Agency
* International Organization for Migration
* International Fund For Agricultural Development
* Oxford Policy Management
* The Hunger Project
* World Bank
* Unicef
* United Nations Development Programme
* University of Copenhagen


## Always walk together with:

Marti :)

