---
title: Keeping my CV up to date with Rmarkdown
author: Andrés Arau
date: '2020-08-20'
slug: CV in R
categories: []
tags:
  - R Markdown
---

**Keeping my CV up to date became a tedious routine**. Not only did I have to repeat the same steps over and over again but I also had to deal with the clunky formatting of Microsoft Word to mantain the style of my resume nice and neat.

On my daily work I have to come up with efficient ways to automatize data processes: collect, clean, analyze and vizualize data in a way that the cycle can be repeated without the workflow crashing. Thus I realized that keeping my resume up to date is technically the same process. New data (a new project) comes in, and this needs to be binded to previous observations (older projects). Then I need to do some editing (cleaning) and display the information on a nicely formatted table (visualizing).

## The solution

I did what I often do for other data management tasks. I organised the information of all my projects through an online dataset (using [zoho creator](https://www.zoho.com/creator/index1.html)), read the data via an API, and clean it in R. Finally, I used [Rmarkdown](https://www.zoho.com/creator/index1.html) to create a template of my CV which is always linked to the latest version of my data. 

The rest just feels like magic! Every time that I work on a new project I just need to update my online database and run my R scripts. **The output is a nice formatted and up to date version of my CV in html and pdf formats!!!**




You can see the html version <a href="https://htmlpreview.github.io/?https://github.com/araupontones/CV/blob/master/Andres_Arau.html" target="_blank">here</a> and the pdf one [here.](https://github.com/araupontones/CV/blob/master/Jaime%20Andr%C3%A9s%20Arau%20Pontones.pdf?raw=TRUE)



All code in <a href="https://github.com/araupontones/CV" target="_blank">GitHub</a>.


### Feels like magic

```{r, eval=TRUE, echo=FALSE}
blogdown::shortcode("youtube", "NadXWhjDd64")
```

### My gratitude to those who have kindly shared examples and ideas online:

- Yihui Xie and Romain Lesur for their book: [_pagedown: Create Paged HTML Documents for Printing from R Markdown_](https://pagedown.rbind.io/)


- Nic Strayer for his post: [_Building a data-driven CV with R_](https://livefreeordichotomize.com/2019/09/04/building_a_data_driven_cv_with_r/)


